# Generated by Django 5.2.17 on 2026-09-29 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], max_length=12)),
                ('handle', models.CharField(max_length=60)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('public_label', models.CharField(choices=[('no_reports', 'No reports yet'), ('needs_checking', 'Needs checking'), ('reports_review', 'Reports received, review ongoing'), ('reported_multiple', 'Reported by multiple users'), ('vouched', 'Vouched by buyers'), ('mixed', 'Mixed'), ('disputed', 'Disputed'), ('resolved', 'Resolved')], default='no_reports', max_length=20)),
                ('label_updated_at', models.DateTimeField(auto_now_add=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_owner', models.BooleanField(default=False)),
                ('claim_code', models.CharField(blank=True, max_length=16)),
                ('indexable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PageLabelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('no_reports', 'No reports yet'), ('needs_checking', 'Needs checking'), ('reports_review', 'Reports received, review ongoing'), ('reported_multiple', 'Reported by multiple users'), ('vouched', 'Vouched by buyers'), ('mixed', 'Mixed'), ('disputed', 'Disputed'), ('resolved', 'Resolved')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_history', to='listings.page')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('send_money', 'M-Pesa Send Money (phone)'), ('till', 'Till number'), ('paybill', 'Paybill'), ('bank', 'Bank account'), ('whatsapp', 'WhatsApp number')], max_length=12)),
                ('value_encrypted', models.TextField()),
                ('value_hash', models.CharField(db_index=True, max_length=64)),
                ('masked', models.CharField(max_length=32)),
                ('registered_name', models.CharField(blank=True, max_length=120)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id_type', 'value_hash'), name='uniq_idtype_hash')],
            },
        ),
        migrations.CreateModel(
            name='PagePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='listings.page')),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_links', to='listings.paymentidentifier')),
            ],
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['handle'], name='listings_pa_handle_f4ecce_idx'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('platform', 'handle'), name='uniq_platform_handle'),
        ),
        migrations.AddConstraint(
            model_name='pagepayment',
            constraint=models.UniqueConstraint(fields=('page', 'identifier'), name='uniq_page_identifier'),
        ),
    ]
