# Generated by Django 5.2.17 on 2026-09-29 10:35

import apps.submissions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_requests', to='listings.page')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CopyrightComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=500)),
                ('infringing_url', models.URLField(max_length=500)),
                ('description', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('upheld', 'Upheld'), ('dismissed', 'Dismissed')], default='submitted', max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copyright_complaints', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copyright_complaints', to='listings.page')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('non_delivery', 'Paid, never delivered'), ('fake_item', 'Fake or counterfeit item'), ('deposit_blocked', 'Paid a deposit, then blocked'), ('wrong_item', 'Wrong or very different item'), ('stolen_video', "Uses someone else's videos"), ('impersonation', 'Impersonating another business')], max_length=20)),
                ('description', models.TextField(max_length=3000)),
                ('amount_kes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'Automated screening'), ('under_review', 'Under review'), ('published', 'Published'), ('disputed', 'Disputed'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='submissions.report')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.page')),
                ('payment_identifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='listings.paymentidentifier')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('whatsapp_identifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_reports', to='listings.paymentidentifier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.submissions.models.evidence_path)),
                ('kind', models.CharField(choices=[('mpesa_message', 'M-Pesa message'), ('chat_screenshot', 'Chat screenshot'), ('page_screenshot', 'Page screenshot'), ('video', 'Video'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('not_reviewed', 'Not reviewed'), ('supported', 'Supported'), ('insufficient', 'Insufficient'), ('contradicted', 'Contradicted'), ('redacted', 'Redacted')], default='not_reviewed', max_length=14)),
                ('moderator_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='submissions.report')),
            ],
        ),
        migrations.CreateModel(
            name='Vouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('proof', models.FileField(upload_to=apps.submissions.models.vouch_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouches', to='listings.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'page'), name='one_vouch_per_user_page')],
            },
        ),
    ]
